// © Ervin Remus Radosavlevici — Private License. Confidential, NDA-bound.
// 100 defensive safeguards mapped to international human-rights law principles.

export interface SafeguardGroup {
  id: string;
  title: string;
  law: string;
  items: string[];
}

export const SAFEGUARD_GROUPS: SafeguardGroup[] = [
  {
    id: "privacy",
    title: "Privacy & data minimisation",
    law: "UDHR Art. 12 · ICCPR Art. 17 · ECHR Art. 8 · GDPR Art. 5",
    items: [
      "Local-first storage — nothing leaves the device automatically",
      "No background network transmission of evidence",
      "No account, email or phone number required",
      "No third-party analytics or advertising trackers",
      "No cookies used for tracking",
      "No fingerprinting of visitors",
      "Only data the owner types is stored",
      "Sensor data is never harvested continuously",
      "Microphone is never opened silently",
      "Camera is never opened silently",
      "Location is never read without an explicit action",
      "Bluetooth scan only on an explicit user click",
      "Data minimisation check before every save",
      "Free-text fields capped to prevent bulk profiling",
      "One-click permanent deletion of all local records",
      "Export is manual, never automatic",
      "Clear on-screen statement of what is collected",
      "No hidden fields inside exported files",
      "No silent clipboard reading",
      "No persistent device identifier is generated",
    ],
  },
  {
    id: "integrity",
    title: "Evidence integrity & anti-interference",
    law: "ICCPR Art. 14 (fair procedure) · Council of Europe e-evidence guidelines",
    items: [
      "SHA-256 integrity hash on every record",
      "Autonomous integrity sentinel re-verifies all records",
      "Tamper detection reports mismatched hashes",
      "Automatic correction of repairable records",
      "Quarantine instead of silent deletion for damaged records",
      "Append-only registry behaviour in normal use",
      "Immutable local timestamp on creation",
      "Record IDs generated with cryptographic randomness",
      "Storage read is schema-validated before display",
      "Corrupt storage never crashes the registry",
      "Duplicate-ID detection",
      "Out-of-order timestamp detection",
      "Chain summary hash across the whole registry",
      "Verification log written in plain language",
      "Manual re-scan available at any time",
      "Scheduled autonomous re-scan while the page is open",
      "Storage-event watcher detects outside modification",
      "Interference counter visible to the owner",
      "Export includes the verification status of each record",
      "Integrity report can be copied for a lawyer or authority",
    ],
  },
  {
    id: "nonaggression",
    title: "Non-aggression & lawful operation",
    law: "ICCPR Art. 17 · national radio & computer-misuse law",
    items: [
      "No RF jamming of any kind",
      "No Bluetooth jamming or flooding",
      "No Wi-Fi deauthentication attacks",
      "No drone takeover or signal spoofing",
      "No remote control of anyone's device",
      "No hacking, intrusion or exploitation tooling",
      "No password or credential capture",
      "No covert surveillance of neighbours",
      "No facial recognition",
      "No voice-print identification",
      "No licence-plate recognition",
      "No automated accusation of any person",
      "No naming of suspects by the system",
      "No scraping of other people's devices",
      "No interception of communications",
      "No signal amplification that could disturb others",
      "No hidden background processes",
      "No self-spreading or persistence mechanism",
      "Clear legal disclaimer on every export",
      "Stated purpose limited to self-defence documentation",
    ],
  },
  {
    id: "dueprocess",
    title: "Due process, dignity & fairness",
    law: "UDHR Art. 1, 11 · ICCPR Art. 14 · ECHR Art. 6",
    items: [
      "Observations kept separate from conclusions",
      "Presumption of innocence stated in the interface",
      "Neutral classification wording, no guilt language",
      "Warning when text may identify a person",
      "Records marked as 'observation', never as 'proof'",
      "Uncertainty of browser sensors disclosed",
      "No automated risk scoring of individuals",
      "No blacklist or watchlist of people",
      "Owner may edit or delete their own entries",
      "Export is human-readable for independent review",
      "Plain-language explanation of every technical term",
      "Right to rectification supported by deletion + re-entry",
      "No profiling of protected characteristics",
      "No inference of health, religion or politics",
      "Advice to report serious matters to lawful authorities",
      "Encouragement of independent expert verification",
      "No claim of legal authority by the application",
      "No claim of spectrum ownership",
      "Accessible contrast and keyboard operation",
      "Content readable without a network connection",
    ],
  },
  {
    id: "security",
    title: "Technical security & confidentiality",
    law: "NDA · Private License · GDPR Art. 32",
    items: [
      "Secure-context (HTTPS) requirement reported",
      "Web Crypto used for hashing, never a custom algorithm",
      "Strict input length limits on every field",
      "All stored data validated on read",
      "No use of eval or dynamic code execution",
      "No injection of untrusted HTML",
      "No external scripts pulled at runtime",
      "No secrets or keys embedded in the page",
      "Exports carry copyright and NDA notices",
      "Confidentiality notice shown before export",
      "Destructive actions require confirmation",
      "Undoable clearing of the entry form",
      "Offline-capable operation",
      "No server-side copy of any record",
      "No shared or multi-tenant storage",
      "Browser capability report for evidential context",
      "Failure states shown, never hidden",
      "Errors never expose internal technical detail",
      "Attribution to Ervin Remus Radosavlevici on every export",
      "Private License terms restated in the registry footer",
    ],
  },
];

export const SAFEGUARD_COUNT = SAFEGUARD_GROUPS.reduce((n, g) => n + g.items.length, 0);
